
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?userUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: accp
server:
  servlet:
    context-path: /springboot52
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.hr.springboot52.entity
  global-config:
    db-config:
      id-type: auto